<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6kzgGfL\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6kzgGfL/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6kzgGfL.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6kzgGfL\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container6kzgGfL\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '6kzgGfL',
    'container.build_id' => '81930a1c',
    'container.build_time' => 1617894698,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6kzgGfL');
